github:
  webhook_secret: "<michelletran-secret>"
  client_id: "Iv23lin7Q85COWWaXFvO"
  client_secret: "30cee85ad2c0e61bcd912aef1e7c5118fc143366"

coverage:
  status:
    project:
      default: false

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: python_code
      name: PythonCode
      paths:
        - "**.py"
    - component_id: everything_else
      name: OtherCode
      paths:
        - "!**.py"
