coverage:
  status:
    project:
      default: false

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: python_code
      name: PythonCode
      paths:
        - "**.py"
    - component_id: everything_else
      name: OtherCode
      paths:
        - "!**.py"
